export const FETCH_CONTENT_START = "FETCH_CONTENT_START";
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS";
export const FETCH_CONTENT_FAIL = "FETCH_CONTENT_FAIL";
export const HYDRATE_BLOGS = "HYDRATE_BLOGS";
export const HYDRATE_PROJECTS = "HYDRATE_PROJECTS";
export const HYDRATE_SECTIONS = "HYDRATE_SECTIONS";

export const FIND_BLOG = "FIND_BLOG";
export const RESET_BLOG = "RESET_BLOG";

export const FIND_PROJECT = "FIND_PROJECT";
export const RESET_PROJECT = "RESET_PROJECT";

export const SET_ABOUT = "SET_ABOUT";
export const SET_CONTACT = "SET_CONTACT";
export const SET_BLOGS = "SET_BLOGS";
export const SET_PROJECTS = "SET_PROJECTS";
